name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        task: [lint, format-check, typecheck, test]
        include:
          - task: lint
            command: pnpm lint
          - task: format-check
            command: pnpm format:check
          - task: typecheck
            command: pnpm typecheck
          - task: test
            command: pnpm test

    name: ${{ matrix.task }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.13.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.task }}
        run: ${{ matrix.command }}

      - name: Upload coverage reports
        if: matrix.task == 'test'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7
